version: "3.9"
services:
  database:
    image: postgres:12.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 54328:5432
  web:
    build:
      context: .
    command: ./docker-entrypoint.sh
    volumes:
       - ./:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
    - ".env"
    stdin_open: true
    tty: true
volumes:
  postgresql_data: